# Generated by Django 4.2.5 on 2024-12-11 17:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='user_profile',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='username',
            new_name='user',
        ),
    ]
